### ISSUE TITLE
Unable to get Group Guid please check your Access Token

### ISSUE THREAD

**Issue by crich80** [codehaveli/codehaveli-bitly-url-shortener#1]
I have an issue clicking Get GUID button as in the immage below:

![image](https://user-images.githubusercontent.com/78030144/105854796-9d88bb80-5fe7-11eb-8143-cf79705597d0.png)

Thanks, 

Danilo.

**Comment by codehaveli** [comment]
Can you confirm the steps please:
1. Enter the Access token
2. Save the Access Token
3. Click on Get GUID

**Comment by crich80** [comment]
Sorry,

I didn't think that I have to save before clicking on button :(

Thank you very much and sorry for the mistake.

Bye,

Danilo.

Il giorno mer 27 gen 2021 alle ore 08:36 Codehaveli <
notifications@github.com> ha scritto:
